INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 1", "category 1", 1000, "06/26/1989", "06/26/1989");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 2", "category 2", 1000, "06/26/1989", "06/26/1989");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 3", "category 3", 1000, "06/26/1989", "06/26/1989");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 4", "category 4", 1000, "06/26/1989", "06/26/1989");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 5", "category 5", 1000, "06/26/1989", "06/26/1989");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 6", "category 6", 1000, "06/26/1989", "06/26/1989");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 7", "category 7", 1000, "06/26/1989", "06/26/1989");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 8", "category 8", 1000, "06/26/1989", "06/26/1989");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 9", "category 9", 1000, "06/26/1989", "06/26/1989");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 10", "category 10", 1000, "06/26/1989", "06/26/1989");

INSERT INTO users (name, age) VALUES ("USER 1", 25);
INSERT INTO users (name, age) VALUES ("USER 2", 25);
INSERT INTO users (name, age) VALUES ("USER 3", 25);
INSERT INTO users (name, age) VALUES ("USER 4", 25);
INSERT INTO users (name, age) VALUES ("USER 5", 25);
INSERT INTO users (name, age) VALUES ("USER 6", 25);
INSERT INTO users (name, age) VALUES ("USER 7", 25);
INSERT INTO users (name, age) VALUES ("USER 8", 25);
INSERT INTO users (name, age) VALUES ("USER 9", 25);
INSERT INTO users (name, age) VALUES ("USER 10", 25);
INSERT INTO users (name, age) VALUES ("USER 11", 25);
INSERT INTO users (name, age) VALUES ("USER 12", 25);
INSERT INTO users (name, age) VALUES ("USER 13", 25);
INSERT INTO users (name, age) VALUES ("USER 14", 25);
INSERT INTO users (name, age) VALUES ("USER 15", 25);
INSERT INTO users (name, age) VALUES ("USER 16", 25);
INSERT INTO users (name, age) VALUES ("USER 17", 25);
INSERT INTO users (name, age) VALUES ("USER 18", 25);
INSERT INTO users (name, age) VALUES ("USER 19", 25);
INSERT INTO users (name, age) VALUES ("USER 20", 25);


INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 5);
